### PR TITLE
fixes #3 bug, better array matching support

### LINKED ISSUE #3: dropped support for array of glob patterns?
With this https://github.com/jonschlinkert/is-match/blob/master/index.js#L39-L43 you drop support for 

``` js
var matcher = require('is-match')
var isMatch = matcher(['*-koaip', '!foo-koa'])

isMatch('x-koaip')
//=> false
```

### PR DESCRIPTION
**Pull request by tunnckoCore**
- replace `isobject` with `is-extendable` - is that okey?
- add test for when fails
- update tests for failing use case and `non-glob string pattern`
- update description to include that it can use object as pattern
- update readme to include when pattern is object
- remove `verb` from dev deps ...? i shocked up why I waits so much, then i see verb lol 
- 100% coverage

### CODE REVIEW

File: index.js [hunk 1]
```diff
@@ -36,10 +36,17 @@ function isMatch(pattern, options) {
     };
   }
 
-  if (Array.isArray(pattern) || isObject(pattern)) {
+  if (Array.isArray(pattern)) {
+    return function (val) {
+      return mm(val, pattern, options).length !== 0;
```
Comment (jonschlinkert) [inline index.js:41]: should we use `mm.any(val, pattern, options)` here? I believe `mm.any()` exits early when a match is found, so it would be faster here...

Comment (tunnckoCore) [inline index.js:41]: lol, im not sure, it's your product :D

Comment (tunnckoCore) [inline index.js:41]: Mm, nope.

I cant agree, it wouldn't be the same as to now and adds totally different meaning, imo

Comment (jonschlinkert) [inline index.js:41]: oh, let me look again...

Comment (jonschlinkert) [inline index.js:41]: K, still seems like `.any()` makes more sense, and `.isMatch()` makes more sense on the string check. We're just returning a boolean. How is `!== 0` better, given that the function will always need to complete the loop before returning it's length?

See https://github.com/jonschlinkert/micromatch#any and https://github.com/jonschlinkert/micromatch#ismatch.

Comment (tunnckoCore) [inline index.js:41]: `.isMatch` accept only string value and string pattern. I use micromatch() to allow to pass multiple values for single pattern

for array pattern I again use `mictomatch()` because same reason - to allow passing multiple values
we cant use `.any()` for array pattern, it have different meaning, imo or i dont understand clear the idea behind `.any()`

i'll do more tests

**Comment by tunnckoCore** [comment]
thanks! :+1: 

dont forget to publish to npm :)

**Comment by jonschlinkert** [comment]
done. thanks again
